/**
 * Regenerates wire-record.json: the exact HTTP request JevDecider emits, captured through a stub
 * transport so it is recorded rather than transcribed. No network call, no credential.
 *
 *   pnpm tsx tools/spikes/gate-jev/record-wire.ts
 *
 * The response half of that file is NOT captured — it is the shape TypeSafe's docs specify and the
 * AI SDK validates against, and it is marked as such in the file. Re-run this when the AI SDK is
 * upgraded: the endpoint path and the `ai-model-id` header are the SDK's, not ours.
 */
import { writeFileSync } from "node:fs";
import { classifyRequest } from "../../../packages/agents/src/decision/decisions.js";
import { JevDecider } from "../../../packages/agents/src/providers/jev.js";

/** Enough of the Gateway's answer to pass the SDK's validation for classify's two questions. */
const RECORDED_RESPONSE_BODY = {
  answers: {
    scope: {
      type: "choice",
      choice: "work",
      probabilities: { work: 0.91, personal: 0.06, unknown: 0.03 },
    },
    priority: {
      type: "choice",
      choice: "today",
      probabilities: { now: 0.08, today: 0.78, week: 0.11, fyi: 0.03 },
    },
  },
  usage: { inputTokens: 412, outputTokens: 0 },
  providerMetadata: { typesafe: { confidence: { scope: 0.91, priority: 0.78 } } },
  modelId: "typesafe-ai/jev-latest",
};

interface Capture {
  url: string;
  method: string;
  headers: Record<string, string>;
  body: unknown;
}

const capture: Capture[] = [];
const stubFetch: typeof fetch = async (input, init) => {
  const headers = new Headers(init?.headers);
  capture.push({
    url: String(input),
    method: init?.method ?? "GET",
    headers: Object.fromEntries(headers.entries()),
    body: JSON.parse(String(init?.body)) as unknown,
  });
  return new Response(JSON.stringify(RECORDED_RESPONSE_BODY), {
    status: 200,
    headers: { "content-type": "application/json" },
  });
};

const decider = new JevDecider({ apiKey: "recorded-placeholder", fetch: stubFetch });
await decider.decide(
  classifyRequest({
    subject: "Q3 invoice needs sign-off",
    body: "Hi Logan — can you approve the Q3 invoice before Friday?",
  }),
);

const first = capture[0];
if (first === undefined) throw new Error("the provider made no request — nothing to record");

// The key is a placeholder, but a token-shaped string in a committed file is a bad habit.
const headers = Object.fromEntries(
  Object.entries(first.headers).map(([k, v]) =>
    k.toLowerCase() === "authorization" ? [k, "Bearer <redacted>"] : [k, v],
  ),
);

writeFileSync(
  new URL("wire-record.json", import.meta.url),
  `${JSON.stringify(
    {
      note: "Generated by record-wire.ts through a stub transport. The request half is captured; the response half is the documented shape, not a capture.",
      recorded_at: new Date().toISOString().slice(0, 10),
      request: { ...first, headers },
      response: {
        source: "docs + AI SDK validation",
        body: RECORDED_RESPONSE_BODY,
      },
    },
    null,
    2,
  )}\n`,
);
console.log(`wrote wire-record.json: ${first.method} ${first.url}`);
